### ISSUE TITLE
2.8.6 release?

### ISSUE THREAD

**Issue by luckman212** [lespea/fse_dump#337]
Seems like the [2.8.6 release][1] may be in error?

I downloaded the arm64 asset from each of the below 2 releases and compared them

```
https://github.com/lespea/fse_dump/releases/download/v2.8.6/fse_dump-v2.8.6-darwin_arm64
https://github.com/lespea/fse_dump/releases/download/v2.0.6/fse_dump-v2.0.6-darwin_arm64
```

```
$ sha256sum fse_dump*
6d52a6d9a312c4819533a7fd126293b76f4cc0fe61be33aec992d36ff8b80d50  fse_dump-v2.0.6-darwin_arm64
6d52a6d9a312c4819533a7fd126293b76f4cc0fe61be33aec992d36ff8b80d50  fse_dump-v2.8.6-darwin_arm64

$ ls -l fse_dump*
-rw-r--r--@ 1 luke  staff  2870680 May 31 12:09 fse_dump-v2.0.6-darwin_arm64
-rw-r--r--  1 luke  staff  2870680 May 31 12:10 fse_dump-v2.8.6-darwin_arm64
```

Even if it was an intentional version bump, the binary still reports itself as v2.0.6
```
$ ./fse_dump-v2.8.6-darwin_arm64 -V
fse_dump 2.0.6
```

Am I missing something?

[1]: https://github.com/lespea/fse_dump/releases/tag/v2.8.6

**Comment by lespea** [comment]
Oh yeah sorry I typod the tag and after realizing it tried deleting it but apparently the CI job kept going and helpfully posted the release.  I deleted it (and the tag) again.

Thanks for letting me know!
